export const GAME_CONFIG = {
  canvasWidth: 960,
  canvasHeight: 640,
  backgroundColor: '#999999',
  snakeColor: '#000000',
  segmentCount: 24,
  headRadius: 18,
  tailRadius: 6,
  radiusFalloff: 0.92,
  segmentSpacing: 12,
  baseSpeed: 220,
  boostMultiplier: 3.5,
  boostEnergyDrain: 85,
  boostMinEnergyFraction: 0.1,
  energyRegenRate: 40,
  turnAcceleration: 2600,
  maxTurnSpeed: 320,
  turnDrag: 2,
  waveAmplitude: 15,
  waveFrequency: 1.2,
  maxEnergy: 100,

  pickupLifetimeSeconds: 14,
  pickupRespawnDelayMin: 2,
  pickupRespawnDelayMax: 4.8,
  pickupInitialSpawnDelay: 0.5,
  /** Spawn-painot musta : keltainen : vihreä. */
  pickupSpawnWeightBlack: 10,
  pickupSpawnWeightYellow: 1,
  pickupSpawnWeightGreen: 2,
  pickupBlackRadius: 11,
  pickupYellowRadius: 10,
  pickupGreenRadius: 10,
  greenHealthRestore: 25,
  pickupSpawnMargin: 48,
  pickupSpawnMinDistFromSnake: 52,
  pickupOverlapSlack: 2,
  growSegmentsPerBlack: 2,
  yellowEnergyRestore: 32,

  maxHealth: 100,
  hazardIdleMin: 11,
  hazardIdleMax: 20,
  hazardWarningSeconds: 1,
  hazardWarningSparkCount: 48,
  hazardSweepSpeed: 540,
  hazardWaveThickness: 52,
  hazardWaveDamage: 20,
  hazardWaveHitCooldown: 0.35,
  hazardEmberDamage: 1,
  hazardEmberHitCooldown: 0.5,
  /** Partikkeleita / s (pidä maltillisena; canvas-shadow + massapiirto on kallista). */
  hazardCrestSpawnRate: 130,
  hazardTrailSpawnRate: 85,
  /** Turva: spawn-laskenta ei käytä dt:tä isompaa kuin tämä → ei spikeja välilehdellä. */
  hazardSpawnDtCap: 0.022,
  /** Enimmäismäärä elossa kerrallaan (vanhimmat poistetaan). */
  hazardFireParticleMax: 380,
  /** Afterburn liikkuu tähän suhteeseen rintaman nopeudesta (0–1). */
  hazardTrailSpeedRatio: 0.78,
  hazardCrestLifeMin: 0.18,
  hazardCrestLifeMax: 0.42,
  hazardTrailLifeMin: 0.85,
  hazardTrailLifeMax: 2.1,
  hazardCrestRadiusMin: 2.2,
  hazardCrestRadiusMax: 5.2,
  hazardTrailRadiusMin: 2.8,
  hazardTrailRadiusMax: 6.2,
  hazardParticleDrag: 1.15,
  /** 0 = ei shadowBluria (iso FPS-voitto). */
  hazardParticleShadowBlur: 0,
  /** Trail-törmäys vain N ensimmäistä segmenttiä (pää + kaula riittää). */
  hazardTrailCollisionSegments: 8,
  hazardTrailCollisionPad: 0,

  /** Asteroidit — hitaat pyörivät mustat palaset (Asteroids-tyyli). */
  asteroidSpawnIntervalMin: 5.5,
  asteroidSpawnIntervalMax: 11,
  asteroidSpawnBatchMin: 1,
  asteroidSpawnBatchMax: 2,
  asteroidMaxAlive: 7,
  asteroidEdgeMargin: 36,
  asteroidDriftSpeedMin: 22,
  asteroidDriftSpeedMax: 48,
  asteroidSpinMax: 0.65,
  asteroidVertMin: 7,
  asteroidVertMax: 11,
  asteroidRadiusMin: 38,
  asteroidRadiusMax: 72,
  asteroidLifeMin: 38,
  asteroidLifeMax: 72,
  asteroidDamage: 11,
  asteroidHitCooldown: 0.42,
  asteroidCollisionSegments: 10,
  asteroidCollisionPad: 2,
  asteroidFillColor: '#101010',
  asteroidStrokeColor: '#3a3a3a',

  orbFloatAmplitudeY: 18,
  orbFloatAmplitudeX: 6,
  orbFloatSpeedPrimary: 2.1,
  orbFloatSpeedSecondary: 1.35,
  orbParticleRateBlack: 14,
  orbParticleRateYellow: 16,
  orbParticleRateGreen: 15,
  orbParticleRadiusBlack: 2.2,
  orbParticleRadiusYellow: 2,
  orbParticleRadiusGreen: 2,
  pickupBlackColor: '#0d0d0d',
  pickupYellowColor: '#e8b923',
  pickupYellowStroke: '#9a7200',
  pickupGreenColor: '#2ecc71',
  pickupGreenStroke: '#1e8448'
};
