export const GAME_CONFIG = {
  canvasWidth: 960,
  canvasHeight: 640,
  backgroundColor: '#999999',
  snakeColor: '#000000',
  segmentCount: 24,
  headRadius: 18,
  tailRadius: 6,
  radiusFalloff: 0.92,
  segmentSpacing: 12,
  baseSpeed: 220,
  boostMultiplier: 3.5,
  boostEnergyDrain: 85,
  boostMinEnergyFraction: 0.1,
  energyRegenRate: 40,
  turnAcceleration: 2600,
  maxTurnSpeed: 320,
  turnDrag: 2,
  waveAmplitude: 15,
  waveFrequency: 1.2,
  maxEnergy: 100,

  pickupLifetimeSeconds: 14,
  pickupRespawnDelayMin: 2,
  pickupRespawnDelayMax: 4.8,
  pickupInitialSpawnDelay: 0.5,
  /** Spawn-suhteet musta : keltainen (esim. 10 ja 1 → ~91 % mustia). */
  pickupSpawnWeightBlack: 10,
  pickupSpawnWeightYellow: 1,
  pickupBlackRadius: 11,
  pickupYellowRadius: 10,
  pickupSpawnMargin: 48,
  pickupSpawnMinDistFromSnake: 52,
  pickupOverlapSlack: 2,
  growSegmentsPerBlack: 2,
  yellowEnergyRestore: 32,

  maxHealth: 100,
  hazardIdleMin: 11,
  hazardIdleMax: 20,
  hazardWarningSeconds: 1,
  hazardWarningSparkCount: 48,
  hazardSweepSpeed: 540,
  hazardWaveThickness: 52,
  hazardWaveDamage: 20,
  hazardWaveHitCooldown: 0.35,
  hazardEmberDamage: 1,
  hazardEmberHitCooldown: 0.5,
  /** Partikkeleita / s rintaman poikkisuunnassa. */
  hazardCrestSpawnRate: 520,
  hazardTrailSpawnRate: 340,
  /** Afterburn liikkuu tähän suhteeseen rintaman nopeudesta (0–1). */
  hazardTrailSpeedRatio: 0.78,
  hazardCrestLifeMin: 0.18,
  hazardCrestLifeMax: 0.42,
  hazardTrailLifeMin: 0.85,
  hazardTrailLifeMax: 2.1,
  hazardCrestRadiusMin: 2.2,
  hazardCrestRadiusMax: 5.2,
  hazardTrailRadiusMin: 2.8,
  hazardTrailRadiusMax: 6.2,
  hazardParticleDrag: 1.15,

  orbFloatAmplitudeY: 18,
  orbFloatAmplitudeX: 6,
  orbFloatSpeedPrimary: 2.1,
  orbFloatSpeedSecondary: 1.35,
  orbParticleRateBlack: 14,
  orbParticleRateYellow: 16,
  orbParticleRadiusBlack: 2.2,
  orbParticleRadiusYellow: 2,
  pickupBlackColor: '#0d0d0d',
  pickupYellowColor: '#e8b923',
  pickupYellowStroke: '#9a7200'
};
